### ISSUE TITLE
ES6 inside NPM package

### ISSUE THREAD

**Issue by danielgent** [helpscout/helix#19]
Hi there,

Great module, big fan of faker and I love what you've done here with schemas.  :heart_eyes: 

I'm just wondering whether you should include `src/` in your `.npmignore`?

Currently when I `npm install` your module, I'm getting ES6 code in the `src` folder (which blows up tools like Jest of course that don't transpile `node_modules`)

Currently I've just got a private fork of Helix to deal with this.

Feel free to ignore this of course, it just still seems the standard to only have ES5 in NPM packages (but I'm far from an expert on creating NPM packages!)

Thanks,
Dan

**Comment by ItsJonQ** [comment]
Heya @danielgent !

That's a great suggestion! I'll take care of that now :)

**Comment by ItsJonQ** [comment]
Heya @danielgent 

Ready for ya in v0.1.1!
https://github.com/helpscout/helix/releases/tag/v0.1.1

I'll close this issue up :)

**Comment by danielgent** [comment]
Thanks a lot! Tested and working for me

**Comment by ItsJonQ** [comment]
@danielgent Amazing! 😍
