### ISSUE TITLE
Multiple identical fixtures generated if seed call is chained

### ISSUE THREAD

**Issue by danielgent** [helpscout/helix#20]
Hi,

Apologies to bother you with another bug, but I thought I'd put this here so future users at least know there is an issue

I've created a code example at https://runkit.com/embed/w8kknlcjgpxw where you can see the following code working
```
const { createSpec, faker } = require('@helpscout/helix')

const exampleSpec = createSpec({
  id: faker.random.number(),  
})

console.log('NOT WORKING: ', JSON.stringify(exampleSpec.seed(123).generate(3)))
```

Which outputs: `"[{\"id\":69646},{\"id\":69646},{\"id\":69646}]"`
This is the same with any `faker` value - they're always the same.  So it looks like the seed is being reset for each generated fixture

In order to get around this, I'm just calling `seed` directly on `faker` like
```
import { faker } from '@helpscout/helix';

faker.seed(123);
```

**Comment by danielgent** [comment]
I haven't tried debugging

But it looks like you're calling `faker.seed(this.seedValue)` in `HelixSpec/index.js` here
https://github.com/helpscout/helix/blob/master/src/HelixSpec/index.js#L80

(Which is pretty similar to my work around anyway)

But then on line 62 you're re-setting

**Comment by ItsJonQ** [comment]
@danielgent No worries at all!

I believe @knicklabs ran into this issue as well recently. We worked around it.. but yes, this should be something we should fix up :)

Thanks again for the heads up! Feel free to comment anytime 🤗

**Comment by ItsJonQ** [comment]
@danielgent Hiya!! The issue is fixed and was released in https://github.com/helpscout/helix/releases/tag/v0.1.2

🎉

**Comment by danielgent** [comment]
Thanks a lot! That makes our tests much nicer
